Interfaces core.hpp and tuple_size.hpp no more has aliases
boostorg/pfr pull request #103
Opened 2022-08-27 12:28 UTC by denzor200

In C++ we can't make specialization for type alias, but for structure can.
This PR will make https://github.com/boostorg/pfr/issues/100 possible to implement.

2022-08-31 18:20 UTC, apolukhin commented
What is the purpose of specializing those two structures?

2022-09-01 07:45 UTC, denzor200 commented
> What is the purpose of specializing those two structures?

Those two structures are not intended to specialize by library's user(i wrote a note in the docs about it, just now). Ability to specialize will be used by library developers.

2022-09-01 07:56 UTC, denzor200 commented
> What is the purpose of specializing those two structures?

It may reduce a lot of code, when i continue integrating pfr into fusion using "VIEW manipulator", like this:
```
struct A
struct B;
struct C;

BOOST_PFR_REGISTRATE_REFLECTABLE(B)

A a{};
B b{};
C c{};
// boost::fusion::for_each(a, [](auto&&){});                     // won't compile
boost::fusion::for_each(b, [](auto&&){});                        // will use default specialization inside
boost::fusion::for_each(boost::pfr::view(c), [](auto&&){});      // will use `boost::pfr::tuple_size<boost::pfr::view_impl<B>>` specialization inside
```

2022-09-01 08:42 UTC, apolukhin requested changes

2022-09-01 08:42 UTC, apolukhin commented on include/boost/pfr/core.hpp
>  /// \code
Permissions on this file changed from 644 to 755. Pleasse do chmod -x

2022-09-01 08:42 UTC, apolukhin commented on include/boost/pfr/core.hpp
> +    using type = std::add_const_t<typename boost::pfr::tuple_element<I, T>::type>;
To avoid additional template instantiations:
```suggestion
    using type = const typename boost::pfr::tuple_element<I, T>::type;
```

2022-09-01 08:42 UTC, apolukhin commented on include/boost/pfr/core.hpp
> +    using type = std::add_volatile_t<typename boost::pfr::tuple_element<I, T>::type>;
To avoid additional template instantiations:
```suggestion
    using type = volatile typename boost::pfr::tuple_element<I, T>::type;
```

2022-09-01 08:42 UTC, apolukhin commented on include/boost/pfr/core.hpp
> +    using type = std::add_cv_t<typename boost::pfr::tuple_element<I, T>::type>;
To avoid additional template instantiations:
```suggestion
    using type = const volatile boost::pfr::tuple_element<I, T>::type;
```

2022-09-01 08:42 UTC, apolukhin commented on test/run/tuple_like_specializable.cpp
> +    static_assert(boost::pfr::tuple_size_v<S> == 20, "");
The more I think about it, the less I like the idea of specializing those traits.

Most part of the library uses `boost::pfr::detail::fields_count<T>()` to get the size. Specializing the `tuple_size` would break random parts of the library without any diagnostics.

2022-09-01 13:50 UTC, denzor200 commented on include/boost/pfr/core.hpp
>  /// \code
I supose it's WSL-side trouble..
Fixed by `chmod 644 include/boost/pfr/core.hpp && chmod 644 include/boost/pfr/tuple_size.hpp && chmod 644 test/run/tuple_like_specializable.cpp`

2022-09-01 13:51 UTC, denzor200 commented on include/boost/pfr/core.hpp
> +    using type = std::add_volatile_t<typename boost::pfr::tuple_element<I, T>::type>;
Resolved, did't work without 'typename'

2022-09-01 13:51 UTC, denzor200 commented on include/boost/pfr/core.hpp
> +    using type = std::add_cv_t<typename boost::pfr::tuple_element<I, T>::type>;
Resolved, did't work without 'typename'

2022-09-01 13:51 UTC, denzor200 commented on test/run/tuple_like_specializable.cpp
> +    static_assert(boost::pfr::tuple_size_v<S> == 20, "");
The usefulness of `tuple_size` specialization has been discussed in the PM.
More details see docs(will be available soon) in PR of https://github.com/boostorg/pfr/issues/102

2022-12-16 16:27 UTC, denzor200 commented
Not actual. It may be reopened in the future when we decide that we really need 'boost::pfr::view' or 'boost::pfr::view_fields', but not now.

2022-12-16 16:27 UTC, closed without merging