Fixed a lot of typos
boostorg/pfr pull request #108
Opened 2022-09-14 14:02 UTC by denzor200

2022-09-14 16:53 UTC, denzor200 commented on include/boost/pfr/io.hpp
> +/// IO manipulator to read/write \aggregate `value` using its IO stream operators or using \forcedlink{io_fields} if operators are not awailable.
We can also fix `awailable` -> `available`

2022-09-14 16:53 UTC, denzor200 commented on include/boost/pfr/io_fields.hpp
>  ///
fix `an` -> `a`

2022-09-24 09:51 UTC, apolukhin requested changes

2022-09-24 09:51 UTC, apolukhin commented on doc/pfr.qbk
> -* T must be aggregate initializable without empty base classes
If I recall correctly, the old text was precise. Loophole implementation could work with aggregates that have non empty base classes

2022-09-24 09:51 UTC, apolukhin commented on doc/pfr.qbk
>  The Boost.PFRs reflection has some limitations that depend on a C++ Standard and compiler capabilities:
You've accidentally changed file permissions to 755 from 644

Please restore the permissions via ’git chmod -x the-affected-files’

2022-11-27 11:11 UTC, denzor200 commented on doc/pfr.qbk
> -* T must be aggregate initializable without empty base classes
I'm sorry for the later answer! Here: https://godbolt.org/z/vWh5zjdqY
Should we fix it?

2022-11-27 11:17 UTC, denzor200 commented on doc/pfr.qbk
>  The Boost.PFRs reflection has some limitations that depend on a C++ Standard and compiler capabilities:
fixed

2023-01-18 16:05 UTC, merged