Simpler way to iterate overfield with the value and the name
boostorg/pfr pull request #171
Opened 2024-05-14 23:32 UTC by Baduit

Add a new function `for_each_field_with_name`

The goal is to be able to do this:
```C++
struct Toto
{
	int a;
	char c;
};

Toto t {5, 'c'};
auto cb = [](std::string_view name, const auto& value){ std::cout << "Name: " << name << " Value: " << value << std::endl; };
boost::pfr::for_each_field_with_name(t, cb);
```

I think this is more user friendly than we way it can be done without this PR:
```C++
auto cb2 = []<std::size_t Index>(const auto& value, std::integral_constant<std::size_t, Index> i)
{
	std::cout << "Name: " << boost::pfr::get_name<Index, Toto>() << " Value: " << value << std::endl;
};
boost::pfr::for_each_field(t, cb2);
```

I tried to make the code of `for_each_field_with_name` as close as possible to `for_each_field`.

I will add new tests if you think this feature could be merged in the future.

I have explored a bit the idea of completing `for_each_field` instead of creating a new function in this branch https://github.com/Baduit/pfr/tree/feature/for_each_field_can_provide_name, most of the work is done and it makes possible to do stuff like this:
```C++
void plop () {
	std::map<std::string, std::string> m;
	auto fill = [&m](std::string_view name, const auto& value){
		m[std::string(name)] = value;
	};

	boost::pfr::for_each_field(SimpleStruct{ 'e', "test"}, fill);

	assert(m.size() == 2);
	assert(m["c"] == "e");
	assert(m["str"] == "test");
}

void plop2 () {
	std::map<std::string, std::string> m;
	std::map<std::string, std::size_t> mi;
	auto fill = [&m, &mi](std::string_view name, const auto& value, std::size_t i){
		m[std::string(name)] = value;
		mi[std::string(name)] = i;
	};

	boost::pfr::for_each_field(SimpleStruct{ 'e', "test"}, fill);
	assert(m.size() == 2);
	assert(m["c"] == "e");
	assert(m["str"] == "test");
	assert(mi.size() == 2);
	assert(mi["c"] == 0);
	assert(mi["str"] == 1);
}
```
Do you think it is a better idea ?

2024-06-21 06:40 UTC, apolukhin requested changes
Looks good!

Please see the comments to make the header changes smaller. Also some docs updates are required

2024-06-21 06:40 UTC, apolukhin commented on include/boost/pfr/core_name.hpp
> +    return detail::for_each_field_with_name(std::forward<T>(value), std::forward<F>(func));
This could be implemented in a simpler way:
```
return boost::pfr::for_each_field(
    std::forward<T>(value),
    [f = std::forward<F>(func)](auto&& t, auto index) mutable {
        constexpr auto name = boost::pfr::gen_name<decltype(index)::value>();
        if constexpr (std::is_invokable_v<F, ?????? >) {
          f(name, t, index);
        } else {
          f(name, t);
        }
    });
```

2024-06-21 06:40 UTC, apolukhin commented on include/boost/pfr/detail/for_each_field_with_name_impl.hpp
> +#endif // BOOST_PFR_DETAIL_FOR_EACH_FIELD_WITH_NAME_IMPL_HPP
Please update the documentation file https://github.com/boostorg/pfr/blob/develop/doc/pfr.qbk . Add after pfr_quick_examples_for_each another table row with pfr_quick_examples_for_each_with_name and add pfr_quick_examples_for_each_with_name example to https://github.com/boostorg/pfr/tree/develop/example

2024-08-27 21:48 UTC, Baduit commented
I updated my branch and thanks to your commit to fix the CI the builds are green

2024-09-13 08:57 UTC, apolukhin approved these changes

2024-09-13 08:57 UTC, merged

2024-09-13 09:16 UTC, apolukhin commented
Many thanks for the PR!