Added gcc-7
boostorg/pfr pull request #75
Opened 2021-04-02 21:12 UTC by denzor200

2021-04-03 18:57 UTC, apolukhin commented on include/boost/pfr/detail/integer_sequence.hpp
> +namespace boost { namespace pfr { namespace detail {
Always include <utility> and check here for the __cpp_lib_integer_sequence feature macro. In that way there's less macro and creepy "do not include before " warnings

2021-04-03 19:01 UTC, apolukhin commented on include/boost/pfr/detail/make_integer_sequence.hpp
> -// Clang unable to use namespace qualified std::integer_sequence in __make_integer_seq.
This comment has reasons :)
Put `using std::integer_sequence;` up above and do not use qualified name in `__make_integer_seq`

2021-05-03 22:38 UTC, denzor200 commented on include/boost/pfr/detail/integer_sequence.hpp
> +namespace boost { namespace pfr { namespace detail {
Not actual

2021-05-03 22:38 UTC, denzor200 commented on include/boost/pfr/detail/make_integer_sequence.hpp
> -// Clang unable to use namespace qualified std::integer_sequence in __make_integer_seq.
Not actual

2021-05-03 22:45 UTC, denzor200 commented
Needs more informative error message in core17_generated.hpp

2021-05-15 09:26 UTC, denzor200 commented
@apolukhin i'm finished

2021-07-24 18:42 UTC, apolukhin requested changes

2021-07-24 18:42 UTC, apolukhin commented on test/Jamfile.v2
> +if ! [ os.environ BOOST_PFR_TEST_WITH_FALLBACK_FOR_BROKEN_STRUCTURED_BINDINGS ]
This does not scales well to other compilers.

See `compiler_supports_loophole` and `loophole_detection.cpp`. Implement the structured binding check in a `structured_binding_detection.cpp` file and use that check.

2022-09-06 10:12 UTC, denzor200 commented
```
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/tuple:807:33: error: implicit instantiation of undefined template 'std::tuple_size<my_struct>'
    : integral_constant<size_t, tuple_size<_Tp>::value> { };
                                ^
./boost/pfr/detail/core17_generated.hpp:57:9: note: in instantiation of template class 'std::tuple_size<const my_struct>' requested here
  auto& [a,b,c] = val; // ====================> Boost.PFR: User-provided type is not a SimpleAggregate.
```
another day, troubles are the same

2022-09-06 10:12 UTC, denzor200 commented on test/Jamfile.v2
> +if ! [ os.environ BOOST_PFR_TEST_WITH_FALLBACK_FOR_BROKEN_STRUCTURED_BINDINGS ]
not actual

2022-09-06 10:13 UTC, denzor200 commented
> ```
> /usr/bin/../lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/tuple:807:33: error: implicit instantiation of undefined template 'std::tuple_size<my_struct>'
>     : integral_constant<size_t, tuple_size<_Tp>::value> { };
>                                 ^
> ./boost/pfr/detail/core17_generated.hpp:57:9: note: in instantiation of template class 'std::tuple_size<const my_struct>' requested here
>   auto& [a,b,c] = val; // ====================> Boost.PFR: User-provided type is not a SimpleAggregate.
> ```
> 
> another day, troubles are the same

i suppose, i know how to fix it https://godbolt.org/z/hWzsojGe6

2023-01-04 14:01 UTC, denzor200 commented
Closed because it's not actual.
Actual PR here: https://github.com/boostorg/pfr/pull/116

2023-01-04 14:01 UTC, closed without merging