Implemented BOOST_NO_PFR macro
boostorg/pfr pull request #86
Opened 2021-06-20 12:32 UTC by denzor200

2021-06-20 19:15 UTC, denzor200 commented
I think this is a bad idea. But we will not close it yet

2022-12-02 14:12 UTC, denzor200 commented on include/boost/pfr/config.hpp
> +#ifndef BOOST_NO_PFR
Add `BOOST_NO_PFR` macro into:
-doc/pfr.qbk (near another macroses)
-test/print_config.cpp (and change inclusion core.hpp -> config.hpp)

2022-12-10 19:55 UTC, denzor200 commented
> I think this is a bad idea.. But we will not close it yet

This idea may become good if we provide the way to override compiler's decision manually. Like this:
```
#define BOOST_NO_PFR 1    //< force set to 'disallowed'
#include <boost/pfr.hpp>  //< compile time error, PFR not supported by user's decision
```
```
#define BOOST_NO_PFR 0    //< force set to 'allowed'
#include <boost/pfr.hpp>  //< good when your compiler really supports pfr
```
```
// #define BOOST_NO_PFR 0  //< let compiler set PFR's status
#include <boost/pfr.hpp>   //< good when your compiler support pfr
```

I'll continue working on it.

2022-12-10 19:57 UTC, denzor200 commented on include/boost/pfr/detail/config.hpp
> +       1. enable C++14;                                                    \
First, we should propose user to take away an `-DBOOST_NO_PFR=1`, if it exist.
Then all another.

2022-12-18 17:33 UTC, apolukhin requested changes

2022-12-18 17:33 UTC, apolukhin commented on doc/pfr.qbk
> +    [[*BOOST_NO_PFR*] [On platforms where Boost.PFR is not supported, the boost/pfr/config.hpp header defines the BOOST_NO_PFR macro equals 1. Defining this macro as 1 before including the header dis
```suggestion
    [[*BOOST_NO_PFR*] [On platforms where Boost.PFR is not supported, the `boost/pfr/config.hpp` header defines the BOOST_NO_PFR macro equal to 1. Defining this macro as 1 before including the header disables the Boost.PFR library. ]]
```

2022-12-18 17:33 UTC, apolukhin commented on doc/pfr.qbk
> +    [[*BOOST_NO_PFR*] [On platforms where Boost.PFR is not supported, the boost/pfr/config.hpp header defines the BOOST_NO_PFR macro equals 1. Defining this macro as 1 before including the header dis
Please change the file permossin back to non-executable

2022-12-18 17:33 UTC, apolukhin commented on include/boost/pfr/detail/config.hpp
> +#include <boost/pfr/config.hpp>
Please change the file permission back to non-executable

2022-12-18 17:33 UTC, apolukhin commented on include/boost/pfr/detail/config.hpp
> +#if BOOST_NO_PFR
Negation in macro is not nice. How about changing the macro name to `BOOST_PFR_ENABLED`?

2022-12-18 17:33 UTC, apolukhin commented on test/print_config.cpp
> -#include <boost/pfr/core.hpp>
chmod -x

2022-12-18 19:50 UTC, apolukhin approved these changes

2022-12-18 19:51 UTC, merged