woraround for msvc compilers <= 1920
boostorg/pfr pull request #88
Opened 2021-07-14 08:58 UTC by alexey-romanov

msvc compilers <= 1920 (VS2017 family compilers and below) have a limit on max 1024 elements in template parameter pack. Limit `max_fields_count` for this particular case.

2021-07-15 07:47 UTC, apolukhin requested changes

2021-07-15 07:47 UTC, apolukhin commented on include/boost/pfr/detail/fields_count.hpp
> +#include <boost/integer/static_min_max.hpp>
Please, don't include other boost librariy header.

PFR should not depend on other parts of boost

2021-07-15 07:47 UTC, apolukhin commented on include/boost/pfr/detail/fields_count.hpp
> +    constexpr std::size_t max_fields_count = boost::static_unsigned_min<sizeof(type) * CHAR_BIT, 1024>::value;
```suggestion
    constexpr std::size_t max_fields_count = (sizeof(type) * CHAR_BIT >= 1024 ? 1024 : sizeof(type) * CHAR_BIT);
```
No very elegant, but works

2021-07-15 09:22 UTC, alexey-romanov commented on include/boost/pfr/detail/fields_count.hpp
> +#include <boost/integer/static_min_max.hpp>
ACK, done.

2021-07-15 09:24 UTC, alexey-romanov commented on include/boost/pfr/detail/fields_count.hpp
> +    constexpr std::size_t max_fields_count = boost::static_unsigned_min<sizeof(type) * CHAR_BIT, 1024>::value;
ok

2021-07-24 13:13 UTC, alexey-romanov commented
@apolukhin changeset updated, please re-review

2021-07-24 18:34 UTC, apolukhin approved these changes
Looks good, many thanks!

2021-07-24 18:35 UTC, merged